<?php
/**
 * Created by PhpStorm.
 * User: andres
 * Date: 2/25/18
 * Time: 5:42 PM
 */

namespace Tests\Unit\Services;


use App\Services\Auth;
use App\User;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\Session;
use Laravel\Passport\Client;
use Laravel\Passport\Passport;
use Tests\TestCase;

class AuthTest extends TestCase
{
    protected $headers;
    protected $user;
    protected $scopes = ['*'];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
        $token = $this->user->createToken('TestToken', $this->scopes)->accessToken;
        $this->headers['Accept'] = 'application/json';
        $this->headers['Authorization'] = 'Bearer '.$token;
    }

    public function get($uri, array $headers = [])
    {
        return parent::get($uri, array_merge($this->headers, $headers));
    }

    /**
     * @test
     */
    public function testRestrictedRoute()
    {
        dd($this->get('/api/v1/hello'));
    }

    /**
     * @test
     */
    public function it_can_generate_an_auth_token()
    {
        $user = factory(User::class)->create();
        $client = factory(Client::class)->create([
            'user_id' => null,
            'personal_access_client' =>false,
            'password_client' => true,
            'revoked' => false,
            'secret' => 'secret',
            'name' => 'yes'
        ]);

        $authService = $this->app->make(Auth::class);
        $loggedIn  = false;

        try {
            $loggedIn = $authService->attemptLogin($client, $user, 'secret');
        }catch (\Exception $e) {
            report($e);
        }
        dd($loggedIn);

        $this->assertNotFalse($loggedIn);
        $this->assertArrayHasKey('access_token', $loggedIn);
        $this->assertArrayHasKey('expires_in', $loggedIn);
    }

    /**
     * @test
     */
    public function it_stores_token_in_an_http_only_cookie()
    {
        $user = factory(User::class)->create();
        $client = factory(Client::class)->create([
            'user_id' => null,
            'personal_access_client' =>false,
            'password_client' => true,
            'revoked' => false,
            'secret' => 'secret',
            'name' => 'yes'
        ]);

        $authService = $this->app->make(Auth::class);

        try {
            $response = $authService->attemptLogin($client, $user, 'secret');
        }catch (\Exception $e) {
            report($e);
        }
    }

    /**
     * @test
     */
    public function it_can_do_normal_login(){
        $user = factory(User::class)->create();
        factory(Client::class)->create([
            'user_id' => null,
            'personal_access_client' =>false,
            'password_client' => true,
            'revoked' => false,
            'secret' => 'secret',
            'name' => 'yes'
        ]);
        $response = $this->json('POST', '/api/v1/login', [
            'email' => $user->email,
            'password' => 'secret'
        ]);
        dd($response);

        $this->assertSame(200, $response->getStatusCode());
        $response->assertJsonStructure(['status', 'message', 'access_token', 'expires_in']);
        $response->assertCookieMissing('refresh_token');
    }

    /**
     * @test
     */
    public function it_can_refresh_an_access_token(){
        $user = factory(User::class)->create();
        factory(Client::class)->create([
            'user_id' => null,
            'personal_access_client' =>false,
            'password_client' => true,
            'revoked' => false,
            'secret' => 'secret',
            'name' => 'yes'
        ]);
        $response = $this->json('POST', '/api/v1/login', [
            'email' => $user->email,
            'password' => 'secret'
        ]);

        $this->assertSame(200, $response->getStatusCode());
        $response->assertJsonStructure(['status', 'message', 'access_token', 'expires_in']);
        $response->assertCookieMissing('refresh_token');
    }

}